version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=espaco_alegria
    volumes:
      - ./postgresql/espaco_alegria_data:/bitnami/postgresql

volumes:
  espaco_alegria_data:
